"""
src/export.py
Export predicted PBR maps to engine‑specific PNG files and package them
into a downloadable ZIP archive.

Pure logic – only NumPy, Pillow, zipfile, io – no Streamlit, no GPU, no state.
"""

import io
import xml.etree.ElementTree as ET
import zipfile

import numpy as np
from PIL import Image, PngImagePlugin


# ---------------------------------------------------------------------------
# Engine‑specific constants and valid names
# ---------------------------------------------------------------------------
_VALID_ENGINES = {"blender", "ue5", "unity_urp", "unity_hdrp", "godot"}

_ENGINE_DOCSTRINGS = {
    "blender": (
        "Blender (OpenGL):\n"
        "  • {asset}_normal.png  — OpenGL normal (Y+ up), RGB channels\n"
        "  • {asset}_roughness.png — roughness in [0, 1], greyscale\n"
        "  • {asset}_metallic.png  — metallic in [0, 1], greyscale\n"
        "(Diffuse/albedo is not generated by MatForge.)"
    ),
    "ue5": (
        "Unreal Engine 5:\n"
        "  • T_{asset}_N.png   — DirectX normal (Y- up), RGB channels\n"
        "  • T_{asset}_ORM.png — ORM packed:\n"
        "        R = Ambient Occlusion (default 255)\n"
        "        G = Roughness\n"
        "        B = Metallic"
    ),
    "unity_urp": (
        "Unity URP (Universal Render Pipeline):\n"
        "  • {asset}_Normal.png              — OpenGL normal, RGB\n"
        "  • {asset}_MetallicSmoothness.png  — RGBA:\n"
        "        R = Metallic\n"
        "        A = Smoothness (1 – Roughness)\n"
        "        G, B unused (0)"
    ),
    "unity_hdrp": (
        "Unity HDRP (High Definition Render Pipeline):\n"
        "  • {asset}_Normal.png   — OpenGL normal, RGB\n"
        "  • {asset}_MaskMap.png  — RGBA Mask Map:\n"
        "        R = Metallic\n"
        "        G = Ambient Occlusion (default 128 = 0.5)\n"
        "        B = Detail Mask (default 128 = 0.5)\n"
        "        A = Smoothness (1 – Roughness)"
    ),
    "godot": (
        "Godot 4 / glTF 2.0:\n"
        "  • {asset}_normal.png — OpenGL normal, RGB\n"
        "  • {asset}_orm.png    — ORM packed:\n"
        "        R = Ambient Occlusion (default 255)\n"
        "        G = Roughness\n"
        "        B = Metallic"
    ),
}


# ===================================================================
# XMP metadata construction and injection
# ===================================================================

def _build_xmp_packet() -> str:
    """Create the XMP metadata packet as a string.

    The packet includes the Adobe-standard envelope and a minimal RDF
    description recording the AI origin of the generated textures.
    """
    # Register all namespaces so that ElementTree uses the expected prefixes
    ET.register_namespace("x", "adobe:ns:meta/")
    ET.register_namespace("rdf", "http://www.w3.org/1999/02/22-rdf-syntax-ns#")
    ET.register_namespace("dc", "http://purl.org/dc/elements/1.1/")
    ET.register_namespace("xmp", "http://ns.adobe.com/xap/1.0/")
    ET.register_namespace("xmpRights", "http://ns.adobe.com/xap/1.0/rights/")

    # Build the RDF tree
    xmpmeta = ET.Element("{adobe:ns:meta/}xmpmeta")
    rdf = ET.SubElement(xmpmeta, "{http://www.w3.org/1999/02/22-rdf-syntax-ns#}RDF")
    desc = ET.SubElement(rdf, "{http://www.w3.org/1999/02/22-rdf-syntax-ns#}Description",
                         attrib={"{http://www.w3.org/1999/02/22-rdf-syntax-ns#}about": ""})
    desc.set("{http://purl.org/dc/elements/1.1/}creator", "MatForge AI System")
    desc.set("{http://purl.org/dc/elements/1.1/}rights",
             "AI-generated content. No copyright protection under EU law (CJEU C-310/17).")
    desc.set("{http://ns.adobe.com/xap/1.0/}CreatorTool", "MatForge v1.0 — PVT-v2-B1 + FPN")
    desc.set("{http://ns.adobe.com/xap/1.0/rights/}Marked", "False")

    xmp_tree = ET.tostring(xmpmeta, encoding="unicode")
    # Wrap in the mandatory Adobe envelope processing instructions
    packet = '<?xpacket begin="\ufeff" id="W5M0MpCehiHzreSzNTczkc9d"?>\n'
    packet += xmp_tree + '\n'
    packet += '<?xpacket end="r"?>'
    return packet


def _inject_xmp_metadata(png_bytes: bytes) -> bytes:
    """Embed XMP provenance metadata into PNG bytes via an iTXt chunk.

    Reopens the PNG with PIL, attaches the XMP packet under the standard
    ``XML:com.adobe.xmp`` keyword, and re-encodes. The caller is responsible
    for passing valid PNG bytes.
    """
    xmp_string = _build_xmp_packet()
    img = Image.open(io.BytesIO(png_bytes))
    info = PngImagePlugin.PngInfo()
    info.add_itxt("XML:com.adobe.xmp", xmp_string, lang="", tkey="")
    out = io.BytesIO()
    img.save(out, format="PNG", pnginfo=info)
    return out.getvalue()


# ===================================================================
# Internal helpers – conversion to PNG bytes
# ===================================================================

def _float_to_uint8(data: np.ndarray) -> np.ndarray:
    """Scale a float32 array from [0, 1] to uint8 [0, 255] with rounding."""
    return np.round(np.clip(data, 0.0, 1.0) * 255.0).astype(np.uint8)


def _array_to_png_bytes(arr: np.ndarray, mode: str) -> bytes:
    """Encode a uint8 numpy array as PNG in‑memory and return the bytes."""
    img = Image.fromarray(arr, mode=mode)
    buffer = io.BytesIO()
    img.save(buffer, format="PNG")
    return buffer.getvalue()


def _pack_normal_opengl(normal: np.ndarray) -> bytes:
    """Pack a float32 OpenGL normal map ([-1, 1] per channel) to PNG bytes.

    Args:
        normal: (H, W, 3) float32, vectors in [-1, 1] (Y+ up).

    Returns:
        PNG file bytes, RGB 8‑bit per channel.
    """
    # Map [-1, 1] → [0, 255]
    packed = _float_to_uint8((normal + 1.0) * 0.5)
    return _array_to_png_bytes(packed, "RGB")


def _pack_normal_directx(normal: np.ndarray) -> bytes:
    """Pack a normal map for DirectX convention (Y‑ down).

    Flips the green channel before mapping to [0, 255].

    Args:
        normal: (H, W, 3) float32, OpenGL normal (Y+ up).

    Returns:
        PNG file bytes, RGB 8‑bit per channel.
    """
    # Work on a copy to avoid mutating the input
    dx_normal = normal.copy()
    dx_normal[..., 1] *= -1.0  # flip G (Y)
    return _pack_normal_opengl(dx_normal)


def _pack_roughness(roughness: np.ndarray) -> bytes:
    """Pack a roughness map (greyscale, [0, 1]) to PNG bytes.

    Args:
        roughness: (H, W) or (H, W, 1) float32.

    Returns:
        PNG file bytes, 8‑bit greyscale.
    """
    r2d = roughness.squeeze()  # (H, W)
    packed = _float_to_uint8(r2d)
    return _array_to_png_bytes(packed, "L")


def _pack_metallic(metallic: np.ndarray) -> bytes:
    """Pack a metallic map (greyscale, [0, 1]) to PNG bytes.

    Args:
        metallic: (H, W) or (H, W, 1) float32.

    Returns:
        PNG file bytes, 8‑bit greyscale.
    """
    m2d = metallic.squeeze()
    packed = _float_to_uint8(m2d)
    return _array_to_png_bytes(packed, "L")


# ---------------------------------------------------------------------------
# Packed map builders for engines using combined textures
# ---------------------------------------------------------------------------

def _build_orm_ue5(roughness: np.ndarray, metallic: np.ndarray) -> bytes:
    """Build UE5 ORM texture: R=AO(255), G=roughness, B=metallic.

    Args:
        roughness: (H, W) or (H, W, 1) float32.
        metallic:  (H, W) or (H, W, 1) float32.

    Returns:
        PNG file bytes, RGB 8‑bit.
    """
    r2d = roughness.squeeze()
    m2d = metallic.squeeze()
    h, w = r2d.shape
    orm = np.zeros((h, w, 3), dtype=np.uint8)
    orm[..., 0] = 255                      # AO default
    orm[..., 1] = _float_to_uint8(r2d)
    orm[..., 2] = _float_to_uint8(m2d)
    return _array_to_png_bytes(orm, "RGB")


def _build_orm_godot(roughness: np.ndarray, metallic: np.ndarray) -> bytes:
    """Build Godot / glTF ORM texture (identical to UE5 ORM layout)."""
    return _build_orm_ue5(roughness, metallic)  # same packing


def _build_metallic_smoothness_urp(
    metallic: np.ndarray, roughness: np.ndarray
) -> bytes:
    """Build Unity URP MetallicSmoothness texture.

    R = Metallic, A = Smoothness (1 – Roughness), G=B=0.

    Args:
        metallic:  (H, W) or (H, W, 1) float32.
        roughness: (H, W) or (H, W, 1) float32.

    Returns:
        PNG file bytes, RGBA 8‑bit.
    """
    m2d = metallic.squeeze()
    r2d = roughness.squeeze()
    h, w = m2d.shape
    out = np.zeros((h, w, 4), dtype=np.uint8)
    out[..., 0] = _float_to_uint8(m2d)                  # R
    out[..., 1] = 0                                     # G
    out[..., 2] = 0                                     # B
    out[..., 3] = _float_to_uint8(1.0 - r2d)            # A (smoothness)
    return _array_to_png_bytes(out, "RGBA")


def _build_mask_map_hdrp(
    metallic: np.ndarray, roughness: np.ndarray
) -> bytes:
    """Build Unity HDRP Mask Map.

    R = Metallic, G = AO (128), B = Detail Mask (128), A = Smoothness.

    Args:
        metallic:  (H, W) or (H, W, 1) float32.
        roughness: (H, W) or (H, W, 1) float32.

    Returns:
        PNG file bytes, RGBA 8‑bit.
    """
    m2d = metallic.squeeze()
    r2d = roughness.squeeze()
    h, w = m2d.shape
    out = np.zeros((h, w, 4), dtype=np.uint8)
    out[..., 0] = _float_to_uint8(m2d)                  # R
    out[..., 1] = 128                                   # G (AO default)
    out[..., 2] = 128                                   # B (Detail Mask)
    out[..., 3] = _float_to_uint8(1.0 - r2d)            # A (smoothness)
    return _array_to_png_bytes(out, "RGBA")


# ===================================================================
# Public wrapper for XMP injection (thin wrapper, kept here for clarity)
# ===================================================================

def add_xmp_metadata(png_bytes: bytes) -> bytes:
    """Embed XMP provenance metadata into PNG bytes.

    This is the public entry point used by the rest of the application.
    """
    return _inject_xmp_metadata(png_bytes)


# ===================================================================
# Public API
# ===================================================================

def export_maps(
    normal: np.ndarray,
    roughness: np.ndarray,
    metallic: np.ndarray,
    asset_name: str = "material",
    engines: list[str] | None = None,
) -> bytes:
    """Package PBR maps as engine‑specific PNGs inside a ZIP archive.

    Args:
        normal:    Normal map, (H, W, 3) float32 in [-1, 1], OpenGL (+Y up).
        roughness: Roughness map, (H, W) or (H, W, 1) float32 in [0, 1].
        metallic:  Metallic map, (H, W) or (H, W, 1) float32 in [0, 1].
        asset_name: Base name used for filenames (no spaces recommended).
        engines:   List of target engines. If ``None``, all five are exported.
                   Valid names: "blender", "ue5", "unity_urp", "unity_hdrp", "godot".

    Returns:
        Bytes of a ZIP file containing all requested PNGs at the root level.

    Raises:
        ValueError: If any element of *engines* is not a recognised engine.
    """
    if engines is None:
        engines = sorted(_VALID_ENGINES)  # deterministic order

    # Validate engine names
    for e in engines:
        if e not in _VALID_ENGINES:
            raise ValueError(
                f"Unknown engine '{e}'. Valid options: {sorted(_VALID_ENGINES)}"
            )

    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        for engine in engines:
            if engine == "blender":
                zf.writestr(
                    f"{asset_name}_normal.png",
                    add_xmp_metadata(_pack_normal_opengl(normal))
                )
                zf.writestr(
                    f"{asset_name}_roughness.png",
                    add_xmp_metadata(_pack_roughness(roughness))
                )
                zf.writestr(
                    f"{asset_name}_metallic.png",
                    add_xmp_metadata(_pack_metallic(metallic))
                )

            elif engine == "ue5":
                zf.writestr(
                    f"T_{asset_name}_N.png",
                    add_xmp_metadata(_pack_normal_directx(normal))
                )
                zf.writestr(
                    f"T_{asset_name}_ORM.png",
                    add_xmp_metadata(_build_orm_ue5(roughness, metallic))
                )

            elif engine == "unity_urp":
                zf.writestr(
                    f"{asset_name}_Normal.png",
                    add_xmp_metadata(_pack_normal_opengl(normal))
                )
                zf.writestr(
                    f"{asset_name}_MetallicSmoothness.png",
                    add_xmp_metadata(_build_metallic_smoothness_urp(metallic, roughness))
                )

            elif engine == "unity_hdrp":
                zf.writestr(
                    f"{asset_name}_Normal.png",
                    add_xmp_metadata(_pack_normal_opengl(normal))
                )
                zf.writestr(
                    f"{asset_name}_MaskMap.png",
                    add_xmp_metadata(_build_mask_map_hdrp(metallic, roughness))
                )

            elif engine == "godot":
                zf.writestr(
                    f"{asset_name}_normal.png",
                    add_xmp_metadata(_pack_normal_opengl(normal))
                )
                zf.writestr(
                    f"{asset_name}_orm.png",
                    add_xmp_metadata(_build_orm_godot(roughness, metallic))
                )

    return zip_buffer.getvalue()


def get_engine_docstring(engine: str) -> str:
    """Return a human‑readable description of the files generated for a given engine.

    Args:
        engine: One of "blender", "ue5", "unity_urp", "unity_hdrp", "godot".

    Returns:
        A multi‑line string describing the file names and channel layout.

    Raises:
        ValueError: If *engine* is not recognised.
    """
    if engine not in _ENGINE_DOCSTRINGS:
        raise ValueError(
            f"Unknown engine '{engine}'. Valid options: {sorted(_ENGINE_DOCSTRINGS.keys())}"
        )
    # Replace placeholder with a generic example name for clarity.
    return _ENGINE_DOCSTRINGS[engine].replace("{asset}", "asset")